apiVersion: v1
kind: ConfigMap
metadata:
  name: adct-https.vs
  namespace: default
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.4.json"
  data: |
    {
      "virtualServer": {
        "frontend": {
          "balance": "round-robin",
          "mode": "http",
          "partition": "k8s",
          "virtualAddress": {
            "bindAddr": "10.1.20.110",
            "port": 443
          },
          "sslProfile": {
          "f5ProfileName": "Common/clientssl"
          }
        },
        "backend": {
          "serviceName": "adct",
          "servicePort": 80,
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "send": "GET /\r\n",
            "timeout": 91
          }]
        }
      }
    }
